### ISSUE TITLE
Create tag components 

### ISSUE THREAD

**Issue by Axw3ll** [BrightCoders-Institute/proyecto-final-team1a#93]
Create a component for the use of tags with the react native paper package

https://callstack.github.io/react-native-paper/4.0/chip.html

![imagen](https://github.com/BrightCoders-Institute/proyecto-final-team1a/assets/88905195/170ebec4-672a-42eb-bebd-4f81d6c0de50)

**Comment by FebernalGober** [comment]
2 componentes: 
- Formulario de tags
- Componente de lista Chip (Prop con array) (Funciona para elminar el chip del array)
un input de texto con icono de agregar

**Comment by BrandonVG** [comment]
https://callstack.github.io/react-native-paper/4.0/icon-button.html
